### PR TITLE
fix: database change to drop the gender column. See MA-25

### PR DESCRIPTION
**Pull request by HassanCehef**
removed references to the gender in candidatures.

PR should be on hold as long as this is not approved by CD.

### CODE REVIEW

**Comment by WikiRik** [comment]
We've got approval of CD, so you can mark it ready for review!

**Comment by HassanCehef** [comment]
I'll change the implementation to keep the data around, since we're not ready to drop it apparently. Shouldn't take long :)

**Comment by WikiRik** [comment]
> I'll change the implementation to keep the data around, since we're not ready to drop it apparently. Shouldn't take long :)

Why? The data is not needed for the candidates. Is there a reason that I've missed?

**Comment by HassanCehef** [comment]
>I'll change the implementation to keep the data around, since we're not ready to drop it apparently. Shouldn't take long :)

Explanation on Jira: this implementation will stay, and the data dropped.

**Comment by HassanCehef** [comment]
I guess we should merge master in this branch to retrigger validation.

**Comment by serge1peshcoff** [comment]
Either that or rebase, true

**Pull request merged**
